# ./.tmuxinator.yml

name: cylcotron
root: ~/

# Optional tmux socket
# socket_name: foo

# Note that the pre and post options have been deprecated and will be replaced by
# project hooks.

# Project hooks

# Runs on project start, always
# on_project_start: command

# Run on project start, the first time
# on_project_first_start: command

# Run on project start, after the first time
# on_project_restart: command

# Run on project exit ( detaching from tmux session )
# on_project_exit: command

# Run on project stop
# on_project_stop: command

# Runs in each window and pane before window/pane specific commands. Useful for setting up interpreter versions.
# pre_window: rbenv shell 2.0.0-p247

# Pass command line options to tmux. Useful for specifying a different tmux.conf.
# tmux_options: -f ~/.tmux.mac.conf

# Change the command to call tmux.  This can be used by derivatives/wrappers like byobu.
# tmux_command: byobu

# Specifies (by name or index) which window will be selected on project startup. If not set, the first window is used.
# startup_window: editor

# Specifies (by index) which pane of the specified window will be selected on project startup. If not set, the first pane is used.
# startup_pane: 1

# Controls whether the tmux session should be attached to automatically. Defaults to true.
# attach: false

windows:
  - k6-ssh: aws ssm start-session --target $K6_INSTANCE_ID
  - postgres-ssh: aws ssm start-session --target $POSTGRES_INSTANCE_ID 
  - user-svc-ssh: 
      - aws ssm start-session --target $USERSVC_INSTANCE_ID
      - sudo su
      - cd /home/ubuntu
      - . ./import-tags.sh
      - PGPASSWORD=$(aws secretsmanager get-secret-value --secret-id cyclotron/commons --region ap-south-1 --query SecretString --output text | jq -r '.PGPASSWORD')
      - cd cyclotron/user
      - go mod tidy
  - k6-jaeger: aws ssm start-session --target $K6_INSTANCE_ID --document-name AWS-StartPortForwardingSession --parameters '{"portNumber":["16686"],"localPortNumber":["16686"]}'
  - k6-grafana: aws ssm start-session --target $K6_INSTANCE_ID --document-name AWS-StartPortForwardingSession --parameters '{"portNumber":["3000"],"localPortNumber":["3000"]}'
  - user-svc-8082: aws ssm start-session --target $USERSVC_INSTANCE_ID --document-name AWS-StartPortForwardingSession --parameters '{"portNumber":["8082"],"localPortNumber":["8082"]}'


