// THIS FILE IS AUTO GENERATED BY GK-CLI DO NOT EDIT!!
package endpoint

import (
	endpoint "github.com/go-kit/kit/endpoint"

	service "cyclotron/user/pkg/service"
)

// Endpoints collects all of the endpoints that compose a profile service. It's
// meant to be used as a helper struct, to collect all of the endpoints into a
// single parameter.
type Endpoints struct {
	LoginEndpoint              endpoint.Endpoint
	RegisterEndpoint           endpoint.Endpoint
	GetUserFromTokenEndpoint   endpoint.Endpoint
	RefreshAccessTokenEndpoint endpoint.Endpoint
}

// New returns a Endpoints struct that wraps the provided service, and wires in all of the
// expected endpoint middlewares
func New(s service.UserService, mdw map[string][]endpoint.Middleware) Endpoints {
	eps := Endpoints{
		GetUserFromTokenEndpoint:   MakeGetUserFromTokenEndpoint(s),
		LoginEndpoint:              MakeLoginEndpoint(s),
		RefreshAccessTokenEndpoint: MakeRefreshAccessTokenEndpoint(s),
		RegisterEndpoint:           MakeRegisterEndpoint(s),
	}
	for _, m := range mdw["Login"] {
		eps.LoginEndpoint = m(eps.LoginEndpoint)
	}
	for _, m := range mdw["Register"] {
		eps.RegisterEndpoint = m(eps.RegisterEndpoint)
	}
	for _, m := range mdw["GetUserFromToken"] {
		eps.GetUserFromTokenEndpoint = m(eps.GetUserFromTokenEndpoint)
	}
	for _, m := range mdw["RefreshAccessToken"] {
		eps.RefreshAccessTokenEndpoint = m(eps.RefreshAccessTokenEndpoint)
	}
	return eps
}
